version: '3.8'

services:
  db:
    image: postgres:13.7

    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app

    ports:
      - '5435:5432'

    volumes:
      - app-db-volume:/var/lib/postgresql/data
      - ./init_db:/init_db
  
volumes:
  app-db-volume:
